### ISSUE TITLE
Add docker-compose.yml file for easier test setup

### ISSUE THREAD

**Issue by KleptoKat** [neo4j/graphql#543]
**Is your feature request related to a problem? Please describe.**
Adding a docker-compose.yml file to the root of the directory would speed up the test setup process for people getting into development. The current process requires you to install Neo4j Desktop, create a new database, install Apoc, create the role, user, password, start the database. It would be nice if we just had to have docker installed on our machine and we could run _docker-compose up_ and it would set us up with a database that was ready to go. I work with a few instances of Neo4j across different projects and it can sometimes get a little unwieldy to manage those instances with Neo4j Desktop. I much prefer running tests/examples with a root docker-compose file, that way we know that all database instances will be setup the same. Additionally, with Neo4j Docker, you can automatically install the latest version of Apoc.

**Describe the solution you'd like**

Something like this:

```yaml
version: '3'

### Pre-configured docker compose file used while running integration tests

services:
  neo4j:
    image: "neo4j:4.2"

    ports:
    - "7474:7474"
    - "7687:7687"
    - "6362:6362"
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_AUTH: neo4j/notasecurepassword
    volumes:
    - "neo4j-graphql-data:/data"
    - "neo4j-graphql-data:/conf"
    - "neo4j-graphql-data:/plugins"
    - "neo4j-graphql-data:/import"
    - "neo4j-graphql-data:/logs"

volumes:
  neo4j-graphql-data:

```

I understand that, as a company, Neo4j probably wants to push Neo4j Desktop but it took me _ages_ to figure out how to use it as a new contributor. It would be much quicker if we had a docker-compose.yml file.

The auth info for neo4j would have to change to neo4j/notasecurepassword across tests/examples if we want it to be quick with neo4j. Note that the NEO4J_AUTH environment variable in this docker container requires that the username is `neo4j`. I like to use hardcoded passwords like `notasecurepassword` so developers know they shouldn't use that password in production. Alternatives like `im a good developer and I change passwords to randomly generated strings in production` and `KleptoKat rocks` also work well.

The `DEVELOPING.md` documentation would have to be updated to something like:

```md

## Testing

In order to run all of the tests, you will need to have a local instance of Neo4j running!
We highly recommend [Neo4j Desktop](https://neo4j.com/download/) to easily get up and running with a local Neo4j instance.
For quicker setup, you can use [Docker and Docker-compose](https://docs.docker.com/get-docker/)

### Neo4j Database Setup Option 1: Neo4j Desktop

1. Install [Neo4j Desktop](https://neo4j.com/download/)

2. Create and start a new DBMS with a database named neo4j (default).

3. Install APOC plugin for that DB.

4. Create appropriate user by running the following command in the DB:

   CREATE USER admin
   SET PASSWORD "password"
   SET PASSWORD CHANGE NOT REQUIRED
   SET STATUS ACTIVE

5. Grant roles to admin user:

   GRANT ROLE admin to admin

### Neo4j Database Setup Option 1: Docker & Docker Compose

1. Install [Docker and Docker-compose](https://docs.docker.com/get-docker/) if you haven't already

2. Run `docker-compose up` in the root directory. Wait for `Remote interface available at http://localhost:7474/`

3. Run tests with `NEO_URL=bolt://localhost:7687 NEO_USER=neo4j NEO_PASSWORD=notasecurepassword yarn test`

```

This would also allow us to test with multiple versions & spin up different versions of neo4j on different ports in the future.
